version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 564559428972.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 564559428972.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 564559428972.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
      - printf '[{"name":"youtube","imageUri":"%s"}]' 564559428972.dkr.ecr.us-east-1.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
